### PR TITLE
PHP 8.3 support added

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by glo71317** [comment]
@froschdesign Can you please review the PR? We are looking for your help to merge this because we are working on Magento Dependencies and support php 8.3 due to laminas dependencies we are blocked so looking forward from your side. Can you please do the needful?

**Comment by Ocramius** [comment]
Please don't spam-ping people

**Comment by glo71317** [comment]
> Please don't spam-ping people

Okay, Can you please help us to whom we can contact to coordinate for merging all laminas PRs

**Review by Ocramius — APPROVED** [review]
Thanks @glo71317

**Pull request merged**
